SELECT * from customers limit 20;

#1.what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;

#2.which customer used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customers
  );

#3.which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#4.compare the average purchase amounts between standard and express shipping
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2)
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

#5.do subscribed customers spend more? compare average spent and total revenue between subscribers and non-subscribers
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

#6.which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#7.segment customers into New,Returning and Loyal based on their total numbber of previous purchase and show the count of each segment
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customers
)

SELECT 
    customer_segment, 
    COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;

#8.what are the top 3 most purchsed products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) as item_rank
from customers
group by category, item_purchased)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

#9.are customers who are repeat buyers(more than previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

#10. what is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;